/* Auto-generated emoji name table — do not edit. */
#include "emoji_sprite.h"

const char * const EMOJI_NAMES[EMOJI_COUNT] = {
    "number sign",
    "asterisk",
    "digit zero",
    "digit one",
    "digit two",
    "digit three",
    "digit four",
    "digit five",
    "digit six",
    "digit seven",
    "digit eight",
    "digit nine",
    "copyright sign",
    "registered sign",
    "double exclamation mark",
    "exclamation question mark",
    "trade mark sign",
    "information source",
    "left right arrow",
    "up down arrow",
    "north west arrow",
    "north east arrow",
    "south east arrow",
    "south west arrow",
    "leftwards arrow with hook",
    "rightwards arrow with hook",
    "watch",
    "hourglass",
    "keyboard",
    "eject symbol",
    "black right-pointing double triangle",
    "black left-pointing double triangle",
    "black up-pointing double triangle",
    "black down-pointing double triangle",
    "black right-pointing double triangle with vertic",
    "black left-pointing double triangle with vertica",
    "black right-pointing triangle with double vertic",
    "alarm clock",
    "stopwatch",
    "timer clock",
    "hourglass with flowing sand",
    "double vertical bar",
    "black square for stop",
    "black circle for record",
    "circled latin capital letter m",
    "black small square",
    "white small square",
    "black right-pointing triangle",
    "black left-pointing triangle",
    "white medium square",
    "black medium square",
    "white medium small square",
    "black medium small square",
    "black sun with rays",
    "cloud",
    "umbrella",
    "snowman",
    "comet",
    "black telephone",
    "ballot box with check",
    "umbrella with rain drops",
    "hot beverage",
    "shamrock",
    "white up pointing index",
    "skull and crossbones",
    "radioactive sign",
    "biohazard sign",
    "orthodox cross",
    "star and crescent",
    "peace symbol",
    "yin yang",
    "wheel of dharma",
    "white frowning face",
    "aries",
    "taurus",
    "gemini",
    "cancer",
    "leo",
    "virgo",
    "libra",
    "scorpius",
    "sagittarius",
    "capricorn",
    "aquarius",
    "pisces",
    "black chess pawn",
    "black spade suit",
    "black club suit",
    "black heart suit",
    "black diamond suit",
    "hot springs",
    "black universal recycling symbol",
    "permanent paper sign",
    "wheelchair symbol",
    "hammer and pick",
    "anchor",
    "crossed swords",
    "scales",
    "alembic",
    "gear",
    "atom symbol",
    "fleur-de-lis",
    "warning sign",
    "male with stroke and male and female sign",
    "medium white circle",
    "medium black circle",
    "coffin",
    "funeral urn",
    "soccer ball",
    "baseball",
    "snowman without snow",
    "sun behind cloud",
    "thunder cloud and rain",
    "ophiuchus",
    "pick",
    "helmet with white cross",
    "chains",
    "no entry",
    "shinto shrine",
    "church",
    "umbrella on ground",
    "fountain",
    "flag in hole",
    "ferry",
    "sailboat",
    "skier",
    "ice skate",
    "person with ball female sign",
    "person with ball male sign",
    "tent",
    "fuel pump",
    "black scissors",
    "white heavy check mark",
    "airplane",
    "envelope",
    "raised fist",
    "raised hand",
    "victory hand",
    "writing hand",
    "pencil",
    "black nib",
    "heavy check mark",
    "heavy multiplication x",
    "latin cross",
    "star of david",
    "sparkles",
    "eight spoked asterisk",
    "eight pointed black star",
    "snowflake",
    "sparkle",
    "cross mark",
    "negative squared cross mark",
    "black question mark ornament",
    "white question mark ornament",
    "white exclamation mark ornament",
    "heavy exclamation mark symbol",
    "heavy heart exclamation mark ornament",
    "heavy black heart",
    "heavy plus sign",
    "heavy minus sign",
    "heavy division sign",
    "black rightwards arrow",
    "curly loop",
    "double curly loop",
    "arrow pointing rightwards then curving upwards",
    "arrow pointing rightwards then curving downwards",
    "leftwards black arrow",
    "upwards black arrow",
    "downwards black arrow",
    "black large square",
    "white large square",
    "white medium star",
    "heavy large circle",
    "wavy dash",
    "part alternation mark",
    "circled ideograph congratulation",
    "circled ideograph secret",
    "mahjong tile red dragon",
    "playing card black joker",
    "negative squared latin capital letter a",
    "negative squared latin capital letter b",
    "negative squared latin capital letter o",
    "negative squared latin capital letter p",
    "negative squared ab",
    "squared cl",
    "squared cool",
    "squared free",
    "squared id",
    "squared new",
    "squared ng",
    "squared ok",
    "squared sos",
    "squared up with exclamation mark",
    "squared vs",
    "squared katakana koko",
    "squared katakana sa",
    "squared cjk unified ideograph-7121",
    "squared cjk unified ideograph-6307",
    "squared cjk unified ideograph-7981",
    "squared cjk unified ideograph-7a7a",
    "squared cjk unified ideograph-5408",
    "squared cjk unified ideograph-6e80",
    "squared cjk unified ideograph-6709",
    "squared cjk unified ideograph-6708",
    "squared cjk unified ideograph-7533",
    "squared cjk unified ideograph-5272",
    "squared cjk unified ideograph-55b6",
    "circled ideograph advantage",
    "circled ideograph accept",
    "cyclone",
    "foggy",
    "closed umbrella",
    "night with stars",
    "sunrise over mountains",
    "sunrise",
    "cityscape at dusk",
    "sunset over buildings",
    "rainbow",
    "bridge at night",
    "water wave",
    "volcano",
    "milky way",
    "earth globe europe-africa",
    "earth globe americas",
    "earth globe asia-australia",
    "globe with meridians",
    "new moon symbol",
    "waxing crescent moon symbol",
    "first quarter moon symbol",
    "waxing gibbous moon symbol",
    "full moon symbol",
    "waning gibbous moon symbol",
    "last quarter moon symbol",
    "waning crescent moon symbol",
    "crescent moon",
    "new moon with face",
    "first quarter moon with face",
    "last quarter moon with face",
    "full moon with face",
    "sun with face",
    "glowing star",
    "shooting star",
    "thermometer",
    "white sun with small cloud",
    "white sun behind cloud",
    "white sun behind cloud with rain",
    "cloud with rain",
    "cloud with snow",
    "cloud with lightning",
    "cloud with tornado",
    "fog",
    "wind blowing face",
    "hot dog",
    "taco",
    "burrito",
    "chestnut",
    "seedling",
    "evergreen tree",
    "deciduous tree",
    "palm tree",
    "cactus",
    "hot pepper",
    "tulip",
    "rose",
    "hibiscus",
    "sunflower",
    "blossom",
    "ear of maize",
    "ear of rice",
    "herb",
    "four leaf clover",
    "maple leaf",
    "fallen leaf",
    "leaf fluttering in wind",
    "mushroom",
    "tomato",
    "aubergine",
    "grapes",
    "melon",
    "watermelon",
    "tangerine",
    "lemon",
    "banana",
    "pineapple",
    "red apple",
    "green apple",
    "pear",
    "peach",
    "cherries",
    "strawberry",
    "hamburger",
    "slice of pizza",
    "meat on bone",
    "poultry leg",
    "rice cracker",
    "rice ball",
    "cooked rice",
    "curry and rice",
    "steaming bowl",
    "spaghetti",
    "bread",
    "french fries",
    "roasted sweet potato",
    "dango",
    "oden",
    "sushi",
    "fried shrimp",
    "fish cake with swirl design",
    "soft ice cream",
    "shaved ice",
    "ice cream",
    "doughnut",
    "cookie",
    "chocolate bar",
    "candy",
    "lollipop",
    "custard",
    "honey pot",
    "shortcake",
    "bento box",
    "pot of food",
    "cooking",
    "fork and knife",
    "teacup without handle",
    "sake bottle and cup",
    "cocktail glass",
    "tropical drink mate drink",
    "beer mug",
    "clinking beer mugs",
    "baby bottle",
    "fork and knife with plate",
    "bottle with popping cork",
    "popcorn",
    "ribbon",
    "wrapped present",
    "birthday cake",
    "jack-o-lantern",
    "christmas tree",
    "father christmas",
    "fireworks",
    "firework sparkler",
    "balloon",
    "party popper",
    "confetti ball",
    "tanabata tree",
    "pine decoration",
    "japanese dolls",
    "carp streamer",
    "wind chime",
    "moon viewing ceremony",
    "school satchel",
    "graduation cap",
    "military medal",
    "reminder ribbon",
    "studio microphone",
    "level slider",
    "control knobs",
    "film frames",
    "admission tickets",
    "carousel horse",
    "ferris wheel",
    "roller coaster",
    "fishing pole and fish",
    "microphone",
    "movie camera",
    "cinema",
    "headphone",
    "artist palette",
    "top hat",
    "circus tent",
    "ticket",
    "clapper board",
    "performing arts",
    "video game",
    "direct hit",
    "slot machine",
    "billiards",
    "game die",
    "bowling",
    "flower playing cards",
    "musical note",
    "multiple musical notes",
    "saxophone",
    "guitar",
    "musical keyboard",
    "trumpet",
    "violin",
    "musical score",
    "running shirt with sash",
    "tennis racquet and ball",
    "ski and ski boot",
    "basketball and hoop",
    "snowboarder",
    "runner female sign",
    "runner male sign",
    "surfer female sign",
    "surfer male sign",
    "sports medal",
    "trophy",
    "horse racing",
    "american football",
    "rugby football",
    "swimmer female sign",
    "swimmer male sign",
    "weight lifter",
    "golfer female sign",
    "golfer male sign",
    "racing motorcycle",
    "racing car",
    "cricket bat and ball",
    "volleyball",
    "field hockey stick and ball",
    "ice hockey stick and puck",
    "table tennis paddle and ball",
    "camping",
    "beach with umbrella",
    "building construction",
    "house buildings",
    "cityscape",
    "derelict house building",
    "classical building",
    "desert",
    "desert island",
    "national park",
    "stadium",
    "house building",
    "house with garden",
    "office building",
    "japanese post office",
    "european post office",
    "hospital",
    "bank",
    "automated teller machine",
    "hotel",
    "love hotel",
    "convenience store",
    "school",
    "department store",
    "factory",
    "izakaya lantern",
    "japanese castle",
    "european castle",
    "rosette",
    "label",
    "badminton racquet and shuttlecock",
    "bow and arrow",
    "amphora",
    "rat",
    "mouse",
    "ox",
    "water buffalo",
    "cow",
    "tiger",
    "leopard",
    "rabbit",
    "cat",
    "cat black large square",
    "dragon",
    "crocodile",
    "whale",
    "snail",
    "snake",
    "ram",
    "goat",
    "sheep",
    "monkey",
    "rooster",
    "chicken",
    "dog",
    "dog safety vest",
    "pig",
    "boar",
    "elephant",
    "octopus",
    "spiral shell",
    "bug",
    "ant",
    "honeybee",
    "lady beetle",
    "fish",
    "tropical fish",
    "blowfish",
    "turtle",
    "hatching chick",
    "baby chick",
    "front-facing baby chick",
    "bird",
    "penguin",
    "koala",
    "poodle",
    "dromedary camel",
    "bactrian camel",
    "dolphin",
    "mouse face",
    "cow face",
    "tiger face",
    "rabbit face",
    "cat face",
    "dragon face",
    "spouting whale",
    "horse face",
    "monkey face",
    "dog face",
    "pig face",
    "frog face",
    "hamster face",
    "wolf face",
    "bear face",
    "bear face snowflake",
    "panda face",
    "pig nose",
    "paw prints",
    "chipmunk",
    "eyes",
    "eye",
    "eye left speech bubble",
    "ear",
    "nose",
    "mouth",
    "tongue",
    "white up pointing backhand index",
    "white down pointing backhand index",
    "white left pointing backhand index",
    "white right pointing backhand index",
    "fisted hand sign",
    "waving hand sign",
    "ok hand sign",
    "thumbs up sign",
    "thumbs down sign",
    "clapping hands sign",
    "open hands sign",
    "crown",
    "womans hat",
    "eyeglasses",
    "necktie",
    "t-shirt",
    "jeans",
    "dress",
    "kimono",
    "bikini",
    "womans clothes",
    "purse",
    "handbag",
    "pouch",
    "mans shoe",
    "athletic shoe",
    "high-heeled shoe",
    "womans sandal",
    "womans boots",
    "footprints",
    "bust in silhouette",
    "busts in silhouette",
    "boy",
    "girl",
    "man",
    "man staff of aesculapius",
    "man scales",
    "man heavy black heart man",
    "man heavy black heart kiss mark man",
    "man ear of rice",
    "man cooking",
    "man baby bottle",
    "man graduation cap",
    "man artist palette",
    "man school",
    "man factory",
    "man personal computer",
    "man briefcase",
    "man wrench",
    "man microscope",
    "man rocket",
    "man fire engine",
    "man probing cane",
    "man red hair",
    "man bald",
    "man white hair",
    "man motorized wheelchair",
    "man manual wheelchair",
    "woman",
    "woman staff of aesculapius",
    "woman scales",
    "woman airplane",
    "woman heavy black heart man",
    "woman heavy black heart woman",
    "woman heavy black heart kiss mark man",
    "woman heavy black heart kiss mark woman",
    "woman ear of rice",
    "woman cooking",
    "woman baby bottle",
    "woman graduation cap",
    "woman artist palette",
    "woman school",
    "woman factory",
    "woman personal computer",
    "woman briefcase",
    "woman wrench",
    "woman microscope",
    "woman rocket",
    "woman fire engine",
    "woman probing cane",
    "woman red hair",
    "woman bald",
    "woman white hair",
    "woman motorized wheelchair",
    "woman manual wheelchair",
    "man and woman holding hands",
    "two men holding hands",
    "two women holding hands",
    "police officer female sign",
    "police officer male sign",
    "woman with bunny ears",
    "woman with bunny ears male sign",
    "bride with veil",
    "bride with veil female sign",
    "bride with veil male sign",
    "person with blond hair female sign",
    "person with blond hair male sign",
    "man with gua pi mao",
    "man with turban female sign",
    "man with turban male sign",
    "older man",
    "older woman",
    "baby",
    "construction worker female sign",
    "construction worker male sign",
    "princess",
    "japanese ogre",
    "japanese goblin",
    "ghost",
    "baby angel",
    "extraterrestrial alien",
    "alien monster",
    "imp",
    "skull",
    "information desk person",
    "guardsman female sign",
    "guardsman male sign",
    "dancer",
    "lipstick",
    "nail polish",
    "face massage female sign",
    "face massage male sign",
    "haircut female sign",
    "haircut male sign",
    "barber pole",
    "syringe",
    "pill",
    "kiss mark",
    "love letter",
    "ring",
    "gem stone",
    "kiss",
    "bouquet",
    "couple with heart",
    "wedding",
    "beating heart",
    "broken heart",
    "two hearts",
    "sparkling heart",
    "growing heart",
    "heart with arrow",
    "green heart",
    "yellow heart",
    "purple heart",
    "heart with ribbon",
    "revolving hearts",
    "heart decoration",
    "diamond shape with a dot inside",
    "electric light bulb",
    "anger symbol",
    "bomb",
    "sleeping symbol",
    "collision symbol",
    "splashing sweat symbol",
    "droplet",
    "dash symbol",
    "pile of poo",
    "flexed biceps",
    "dizzy symbol",
    "speech balloon",
    "thought balloon",
    "white flower",
    "hundred points symbol",
    "money bag",
    "currency exchange",
    "heavy dollar sign",
    "credit card",
    "banknote with yen sign",
    "banknote with dollar sign",
    "banknote with euro sign",
    "banknote with pound sign",
    "money with wings",
    "chart with upwards trend and yen sign",
    "seat",
    "personal computer",
    "briefcase",
    "minidisc",
    "floppy disk",
    "optical disc",
    "dvd",
    "file folder",
    "open file folder",
    "page with curl",
    "page facing up",
    "calendar",
    "tear-off calendar",
    "card index",
    "chart with upwards trend",
    "chart with downwards trend",
    "bar chart",
    "clipboard",
    "pushpin",
    "round pushpin",
    "paperclip",
    "straight ruler",
    "triangular ruler",
    "bookmark tabs",
    "ledger",
    "notebook",
    "notebook with decorative cover",
    "closed book",
    "open book",
    "green book",
    "blue book",
    "orange book",
    "books",
    "name badge",
    "scroll",
    "memo",
    "telephone receiver",
    "pager",
    "fax machine",
    "satellite antenna",
    "public address loudspeaker",
    "cheering megaphone",
    "outbox tray",
    "package",
    "e-mail symbol",
    "incoming envelope",
    "envelope with downwards arrow above",
    "closed mailbox with lowered flag",
    "closed mailbox with raised flag",
    "open mailbox with raised flag",
    "open mailbox with lowered flag",
    "postbox",
    "postal horn",
    "newspaper",
    "mobile phone",
    "mobile phone with rightwards arrow at left",
    "vibration mode",
    "mobile phone off",
    "no mobile phones",
    "antenna with bars",
    "camera",
    "camera with flash",
    "video camera",
    "television",
    "radio",
    "videocassette",
    "film projector",
    "prayer beads",
    "twisted rightwards arrows",
    "clockwise rightwards and leftwards open circle a",
    "clockwise rightwards and leftwards open circle a",
    "clockwise downwards and upwards open circle arro",
    "anticlockwise downwards and upwards open circle ",
    "low brightness symbol",
    "high brightness symbol",
    "speaker with cancellation stroke",
    "speaker",
    "speaker with one sound wave",
    "speaker with three sound waves",
    "battery",
    "electric plug",
    "left-pointing magnifying glass",
    "right-pointing magnifying glass",
    "lock with ink pen",
    "closed lock with key",
    "key",
    "lock",
    "open lock",
    "bell",
    "bell with cancellation stroke",
    "bookmark",
    "link symbol",
    "radio button",
    "back with leftwards arrow above",
    "end with leftwards arrow above",
    "on with exclamation mark with left right arrow a",
    "soon with rightwards arrow above",
    "top with upwards arrow above",
    "no one under eighteen symbol",
    "keycap ten",
    "input symbol for latin capital letters",
    "input symbol for latin small letters",
    "input symbol for numbers",
    "input symbol for symbols",
    "input symbol for latin letters",
    "fire",
    "electric torch",
    "wrench",
    "hammer",
    "nut and bolt",
    "hocho",
    "pistol",
    "microscope",
    "telescope",
    "crystal ball",
    "six pointed star with middle dot",
    "japanese symbol for beginner",
    "black square button",
    "white square button",
    "large red circle",
    "large blue circle",
    "large orange diamond",
    "large blue diamond",
    "small orange diamond",
    "small blue diamond",
    "up-pointing red triangle",
    "down-pointing red triangle",
    "up-pointing small red triangle",
    "down-pointing small red triangle",
    "om symbol",
    "dove of peace",
    "kaaba",
    "mosque",
    "synagogue",
    "menorah with nine branches",
    "clock face one oclock",
    "clock face two oclock",
    "clock face three oclock",
    "clock face four oclock",
    "clock face five oclock",
    "clock face six oclock",
    "clock face seven oclock",
    "clock face eight oclock",
    "clock face nine oclock",
    "clock face ten oclock",
    "clock face eleven oclock",
    "clock face twelve oclock",
    "clock face one-thirty",
    "clock face two-thirty",
    "clock face three-thirty",
    "clock face four-thirty",
    "clock face five-thirty",
    "clock face six-thirty",
    "clock face seven-thirty",
    "clock face eight-thirty",
    "clock face nine-thirty",
    "clock face ten-thirty",
    "clock face eleven-thirty",
    "clock face twelve-thirty",
    "candle",
    "mantelpiece clock",
    "hole",
    "man in business suit levitating",
    "sleuth or spy",
    "sleuth or spy female sign",
    "dark sunglasses",
    "spider",
    "spider web",
    "joystick",
    "man dancing",
    "linked paperclips",
    "lower left ballpoint pen",
    "lower left fountain pen",
    "lower left paintbrush",
    "lower left crayon",
    "raised hand with fingers splayed",
    "reversed hand with middle finger extended",
    "raised hand with part between middle and ring fi",
    "black heart",
    "desktop computer",
    "printer",
    "three button mouse",
    "trackball",
    "frame with picture",
    "card index dividers",
    "card file box",
    "file cabinet",
    "wastebasket",
    "spiral note pad",
    "spiral calendar pad",
    "compression",
    "old key",
    "rolled-up newspaper",
    "dagger knife",
    "speaking head in silhouette",
    "right anger bubble",
    "ballot box with ballot",
    "world map",
    "tokyo tower",
    "statue of liberty",
    "silhouette of japan",
    "moyai",
    "grinning face",
    "grinning face with smiling eyes",
    "face with tears of joy",
    "smiling face with open mouth",
    "smiling face with open mouth and smiling eyes",
    "smiling face with open mouth and cold sweat",
    "smiling face with open mouth and tightly-closed ",
    "smiling face with halo",
    "smiling face with horns",
    "winking face",
    "smiling face with smiling eyes",
    "face savouring delicious food",
    "relieved face",
    "smiling face with heart-shaped eyes",
    "smirking face",
    "neutral face",
    "expressionless face",
    "unamused face",
    "face with cold sweat",
    "pensive face",
    "confused face",
    "confounded face",
    "kissing face",
    "face throwing a kiss",
    "kissing face with smiling eyes",
    "kissing face with closed eyes",
    "face with stuck-out tongue",
    "face with stuck-out tongue and winking eye",
    "face with stuck-out tongue and tightly-closed ey",
    "disappointed face",
    "worried face",
    "angry face",
    "pouting face",
    "crying face",
    "face with look of triumph",
    "disappointed but relieved face",
    "frowning face with open mouth",
    "anguished face",
    "fearful face",
    "weary face",
    "sleepy face",
    "tired face",
    "grimacing face",
    "loudly crying face",
    "face with open mouth",
    "hushed face",
    "face with open mouth and cold sweat",
    "face screaming in fear",
    "astonished face",
    "flushed face",
    "sleeping face",
    "dizzy face",
    "face without mouth",
    "face without mouth fog",
    "face with medical mask",
    "grinning cat face with smiling eyes",
    "cat face with tears of joy",
    "smiling cat face with open mouth",
    "smiling cat face with heart-shaped eyes",
    "cat face with wry smile",
    "kissing cat face with closed eyes",
    "pouting cat face",
    "crying cat face",
    "weary cat face",
    "slightly frowning face",
    "slightly smiling face",
    "upside-down face",
    "face with no good gesture",
    "face with ok gesture",
    "person bowing deeply",
    "see-no-evil monkey",
    "hear-no-evil monkey",
    "speak-no-evil monkey",
    "happy person raising one hand female sign",
    "happy person raising one hand male sign",
    "person raising both hands in celebration",
    "person frowning female sign",
    "person frowning male sign",
    "person with pouting face female sign",
    "person with pouting face male sign",
    "person with folded hands",
    "rocket",
    "helicopter",
    "steam locomotive",
    "railway car",
    "high-speed train",
    "high-speed train with bullet nose",
    "train",
    "metro",
    "light rail",
    "station",
    "tram",
    "tram car",
    "bus",
    "oncoming bus",
    "trolleybus",
    "bus stop",
    "minibus",
    "ambulance",
    "fire engine",
    "police car",
    "oncoming police car",
    "taxi",
    "oncoming taxi",
    "automobile",
    "oncoming automobile",
    "recreational vehicle",
    "delivery truck",
    "articulated lorry",
    "tractor",
    "monorail",
    "mountain railway",
    "suspension railway",
    "mountain cableway",
    "aerial tramway",
    "ship",
    "rowboat female sign",
    "rowboat male sign",
    "speedboat",
    "horizontal traffic light",
    "vertical traffic light",
    "construction sign",
    "police cars revolving light",
    "door",
    "no entry sign",
    "smoking symbol",
    "no smoking symbol",
    "put litter in its place symbol",
    "do not litter symbol",
    "potable water symbol",
    "non-potable water symbol",
    "bicycle",
    "no bicycles",
    "bicyclist female sign",
    "bicyclist male sign",
    "pedestrian female sign",
    "pedestrian male sign",
    "no pedestrians",
    "children crossing",
    "mens symbol",
    "womens symbol",
    "restroom",
    "baby symbol",
    "toilet",
    "water closet",
    "shower",
    "bath",
    "bathtub",
    "passport control",
    "customs",
    "baggage claim",
    "left luggage",
    "couch and lamp",
    "sleeping accommodation",
    "shopping bags",
    "bellhop bell",
    "bed",
    "place of worship",
    "octagonal sign",
    "shopping trolley",
    "hindu temple",
    "hut",
    "elevator",
    "wheel",
    "ring buoy",
    "hammer and wrench",
    "shield",
    "oil drum",
    "motorway",
    "railway track",
    "motor boat",
    "small airplane",
    "airplane departure",
    "airplane arriving",
    "satellite",
    "passenger ship",
    "scooter",
    "motor scooter",
    "canoe",
    "sled",
    "flying saucer",
    "skateboard",
    "auto rickshaw",
    "pickup truck",
    "roller skate",
    "large orange circle",
    "large yellow circle",
    "large green circle",
    "large purple circle",
    "large brown circle",
    "large red square",
    "large blue square",
    "large orange square",
    "large yellow square",
    "large green square",
    "large purple square",
    "large brown square",
    "heavy equals sign",
    "pinched fingers",
    "white heart",
    "brown heart",
    "pinching hand",
    "zipper-mouth face",
    "money-mouth face",
    "face with thermometer",
    "nerd face",
    "thinking face",
    "face with head-bandage",
    "robot face",
    "hugging face",
    "sign of the horns",
    "call me hand",
    "raised back of hand",
    "left-facing fist",
    "right-facing fist",
    "handshake",
    "hand with index and middle fingers crossed",
    "i love you hand sign",
    "face with cowboy hat",
    "clown face",
    "nauseated face",
    "rolling on the floor laughing",
    "drooling face",
    "lying face",
    "face palm",
    "sneezing face",
    "face with one eyebrow raised",
    "grinning face with star eyes",
    "grinning face with one large and one small eye",
    "face with finger covering closed lips",
    "serious face with symbols covering mouth",
    "smiling face with smiling eyes and hand covering",
    "face with open mouth vomiting",
    "shocked face with exploding head",
    "pregnant woman",
    "breast-feeding",
    "palms up together",
    "selfie",
    "man in tuxedo",
    "man in tuxedo female sign",
    "man in tuxedo male sign",
    "mother christmas",
    "shrug",
    "shrug male sign",
    "person doing cartwheel",
    "person doing cartwheel male sign",
    "juggling female sign",
    "juggling male sign",
    "fencer",
    "wrestlers",
    "water polo female sign",
    "water polo male sign",
    "handball",
    "handball female sign",
    "diving mask",
    "wilted flower",
    "drum with drumsticks",
    "clinking glasses wine glass",
    "tumbler glass",
    "spoon",
    "goal net",
    "first place medal",
    "second place medal",
    "third place medal",
    "boxing glove",
    "martial arts uniform",
    "curling stone",
    "lacrosse stick and ball",
    "softball",
    "flying disc",
    "croissant",
    "avocado",
    "cucumber",
    "bacon",
    "potato",
    "carrot",
    "baguette bread",
    "green salad",
    "shallow pan of food",
    "stuffed flatbread",
    "egg",
    "glass of milk",
    "peanuts",
    "kiwifruit",
    "pancakes",
    "dumpling",
    "fortune cookie",
    "takeout box",
    "chopsticks",
    "bowl with spoon",
    "cup with straw",
    "coconut",
    "broccoli",
    "pie",
    "pretzel",
    "cut of meat",
    "sandwich",
    "canned food",
    "leafy green",
    "mango",
    "moon cake",
    "bagel",
    "smiling face with smiling eyes and three hearts",
    "yawning face",
    "face with party horn and party hat",
    "face with uneven eyes and wavy mouth",
    "overheated face",
    "freezing face",
    "ninja",
    "disguised face",
    "face with pleading eyes",
    "sari",
    "lab coat",
    "goggles",
    "hiking boot",
    "flat shoe",
    "crab",
    "lion face",
    "scorpion",
    "turkey",
    "unicorn face",
    "eagle",
    "duck",
    "bat",
    "shark",
    "owl",
    "fox face",
    "butterfly",
    "deer",
    "gorilla",
    "lizard",
    "rhinoceros",
    "shrimp",
    "squid",
    "giraffe face",
    "zebra face",
    "hedgehog",
    "sauropod",
    "t-rex",
    "cricket",
    "kangaroo",
    "llama",
    "peacock",
    "hippopotamus",
    "parrot",
    "raccoon",
    "lobster",
    "mosquito",
    "microbe",
    "badger",
    "swan",
    "mammoth",
    "dodo",
    "sloth",
    "otter",
    "orangutan",
    "skunk",
    "flamingo",
    "oyster",
    "beaver",
    "bison",
    "seal",
    "guide dog",
    "probing cane",
    "bone",
    "leg leg",
    "foot",
    "tooth",
    "superhero",
    "superhero female sign",
    "superhero male sign",
    "supervillain female sign",
    "safety vest",
    "ear with hearing aid",
    "motorized wheelchair",
    "manual wheelchair",
    "mechanical arm",
    "mechanical leg",
    "cheese wedge",
    "cupcake",
    "salt shaker",
    "beverage box",
    "garlic",
    "onion",
    "falafel",
    "waffle",
    "butter",
    "ice cube",
    "bubble tea",
    "troll",
    "standing person",
    "standing person female sign",
    "standing person male sign",
    "kneeling person",
    "deaf person",
    "face with monocle",
    "adult",
    "adult staff of aesculapius",
    "adult scales",
    "adult airplane",
    "adult ear of rice",
    "adult cooking",
    "adult baby bottle",
    "adult christmas tree",
    "adult graduation cap",
    "adult artist palette",
    "adult school",
    "adult factory",
    "adult personal computer",
    "adult briefcase",
    "adult wrench",
    "adult microscope",
    "adult rocket",
    "adult fire engine",
    "adult probing cane",
    "adult red hair",
    "adult bald",
    "adult white hair",
    "adult motorized wheelchair",
    "adult manual wheelchair",
    "child",
    "older adult",
    "bearded person female sign",
    "person with headscarf",
    "person in steamy room female sign",
    "person in steamy room male sign",
    "person climbing female sign",
    "person climbing male sign",
    "person in lotus position female sign",
    "person in lotus position male sign",
    "mage female sign",
    "mage male sign",
    "fairy",
    "vampire female sign",
    "vampire male sign",
    "merperson",
    "elf female sign",
    "elf male sign",
    "genie",
    "zombie female sign",
    "zombie male sign",
    "brain",
    "orange heart",
    "billed cap",
    "scarf",
    "gloves",
    "coat",
    "socks",
    "red gift envelope",
    "firecracker",
    "jigsaw puzzle piece",
    "test tube",
    "petri dish",
    "dna double helix",
    "compass",
    "abacus",
    "fire extinguisher",
    "toolbox",
    "brick",
    "magnet",
    "luggage",
    "lotion bottle",
    "spool of thread",
    "ball of yarn",
    "safety pin",
    "teddy bear",
    "broom",
    "basket",
    "roll of paper",
    "bar of soap",
    "sponge",
    "receipt",
    "nazar amulet",
    "ballet shoes",
    "one-piece swimsuit",
    "briefs",
    "shorts",
    "thong sandal",
    "light blue heart",
    "drop of blood",
    "adhesive bandage",
    "stethoscope",
    "x-ray",
    "yo-yo",
    "kite",
    "parachute",
    "boomerang",
    "magic wand",
    "pinata",
    "nesting dolls",
    "ringed planet",
    "chair",
    "razor",
    "axe",
    "diya lamp",
    "banjo",
    "military helmet",
    "accordion",
    "long drum",
    "coin",
    "carpentry saw",
    "screwdriver",
    "ladder",
    "hook",
    "mirror",
    "window",
    "plunger",
    "sewing needle",
    "knot",
    "bucket",
    "mouse trap",
    "toothbrush",
    "headstone",
    "placard",
    "rock",
    "mirror ball",
    "identification card",
    "low battery",
    "hamsa",
    "fly",
    "worm",
    "beetle",
    "cockroach",
    "potted plant",
    "wood",
    "feather",
    "lotus",
    "coral",
    "empty nest",
    "nest with eggs",
    "hyacinth",
    "anatomical heart",
    "lungs",
    "people hugging",
    "person with crown",
    "donkey",
    "blueberries",
    "bell pepper",
    "olive",
    "flatbread",
    "tamale",
    "fondue",
    "teapot",
    "pouring liquid",
    "beans",
    "jar",
    "melting face",
    "saluting face",
    "face with open eyes and hand over mouth",
    "face with peeking eye",
    "face with diagonal mouth",
    "dotted line face",
    "biting lip",
    "bubbles",
    "hand with index finger and thumb crossed",
    "rightwards hand",
    "leftwards hand",
    "palm down hand",
    "palm up hand",
    "index pointing at the viewer",
    "heart hands"
};
